### ISSUE TITLE
In GUI installer, partitions aren't detected.

### ISSUE THREAD

**Issue by FredBezies** [VeltTechnologies/vos-installer#1]
Hello. I was looking at your project, and I found a 0.3 ISO I downloaded.

I wanted to test your installer in a VirtualBox machine. I set up partitions using cgdisk. Then I launched installer GUI. Partitions were not detected. Rebooted. Same bug.

See screenshot.

![003](https://user-images.githubusercontent.com/8571419/29362952-4776acb4-828e-11e7-8e63-cf6b6bd8de57.png)

Any idea of what is going on here?

Thanks!

**Comment by azsn** [comment]
This issue should be already fixed, but I just haven't updated the ISO yet. Run "sudo pacman -Sy veltos-install" to update the installer and see if that solves the problem. If not, let me know! Thanks!

**Comment by FredBezies** [comment]
Indeed, I downloaded wrong ISO. But there is another bug I'm going to open soon.
