### ISSUE TITLE
Installer ask me for an EFI boot partition within a bios VirtualBox machine :(

### ISSUE THREAD

**Issue by FredBezies** [VeltTechnologies/vos-installer#2]
I noticed that installer asks me to set up an EFI boot partition, but my VirtualBox machine is bios based...

Got an error and installer is crashing :(

![virtualbox_veltos 0 3_16_08_2017_17_23_38](https://user-images.githubusercontent.com/8571419/29371102-beb5ef88-82a7-11e7-81c3-039e092c3be2.png)

Is there any way to bypass this ? Or is VeltOS going to be EFI only ?

**Comment by azsn** [comment]
The installer only installs the rEFInd boot manager, but you can install your own if you want. So that's definitely a bug. I think I know what the problem is; give me a few minutes to work on it.

**Comment by azsn** [comment]
Repo updated, run sudo pacman -Sy veltos-install. Hopefully it's fixed now.

**Comment by FredBezies** [comment]
Fixed. So what about installing grub2 instead?
